apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-aws-creds
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: ubbagent
type: Opaque
data:
  aws_access_key_id: {{ required "secrets.awsAccessKeyId field is required!" .Values.secrets.awsAccessKeyId | b64enc | quote }}
  aws_secret_access_key: {{ required "secrets.awsSecretAccessKey field is required!" .Values.secrets.awsSecretAccessKey | b64enc | quote }}
{{- if .Values.secrets.awsIamRole }}
  role: {{ .Values.secrets.awsIamRole | trim | b64enc | quote }}
{{- end }}

