apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-service
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: pelican-web
{{- if .Values.pelican.tls.enabled }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.pelican.tls.certificateARN }}
{{- end }}

spec:
  type: {{ .Values.pelican.service.type }}
  loadBalancerSourceRanges:
    {{- range $IP := (split "," .Values.pelican.service.loadBalancerSourceRanges) }}
    - {{ $IP }}
    {{- end }}
  ports:
{{- if .Values.pelican.tls.enabled }}
    - name: https
      port: 443
      targetPort: 8080
{{- else }}
    - name: pelicanui-1
      port: 8080
      protocol: TCP
      targetPort: 8080
{{- end }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: pelican-web
    app: pelican-web
