kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pelican-web-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Release.Name }}-pelican-web-sc
  resources:
    requests:
      storage: 20Gi
