apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pelican-web-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Release.Name }}-pelican-web-pv
  resources:
    requests:
      storage: {{ .Values.pelican.persistence.size }}
  storageClassName: {{ .Values.pelican.persistence.storageClass }}

