apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pelican-additional-files-pvc
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: pelican-web
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Release.Name }}-pelican-additional-files-sc
  resources:
    requests:
      storage: 5Gi
