kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: {{ .Release.Name }}-pelican-web-sc
reclaimPolicy: Retain
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
